# Generated by Django 3.1.2 on 2020-10-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asia',
        ),
    ]
